# site settings
title: Proyectistas A&J
subtitle: Arquitectura e Interiorismo
email: proyecticas_ayj@gmail.com
description: Estudio de arquitectura e interiorismo. Diseño contemporáneo, funcionalidad y detalle.
baseurl: ""
url: https://proyectistasayj.github.io

author: Angelica, Carla Peralta  
dirección: Av. 20 de Marzo 145
ciudad: San Agustín de Cajas - Huancayo
departamento: Junín
pais: Perú
Celular: +51 902148221


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram: https://www.instagram.com/proyectistas_ayj
  Tiktok: https://www.tiktok.com/@proyectistas_ayj
  Facebook: https://www.facebook.com/aj.proyectistas
  LinkedIn:
  GitHub:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
